#!/bin/sh

set -e
set -o xtrace

# Replace /etc/resolv.conf.ORIG with new resolver
if test -f "/etc/resolv.conf.ORIG"; then
    cat > /etc/resolv.conf.ORIG << EOF
nameserver 127.0.0.53
options edns0
search openstacklocal
EOF

else
    echo "/etc/resolv.conf.ORIG not found"
fi
