#!/bin/sh

set -e
set -o xtrace

# Replace /etc/resolv.conf.ORIG with new resolver
if test -f "/etc/resolv.conf.ORIG"; then
    echo > /etc/resolv.conf.ORIG
else
    echo "/etc/resolv.conf.ORIG not found"
fi
