#!/bin/sh
#
# K2HDKC DBaaS based on Trove
#
# Copyright 2020 Yahoo Japan Corporation
#
# K2HDKC DBaaS is a Database as a Service compatible with Trove which
# is DBaaS for OpenStack.
# Using K2HR3 as backend and incorporating it into Trove to provide
# DBaaS functionality. K2HDKC, K2HR3, CHMPX and K2HASH are components
# provided as AntPickax.
# 
# For the full copyright and license information, please view
# the license file that was distributed with this source code.
#
# AUTHOR:   Hirotaka Wakabayashi
# CREATE:   Mon Sep 14 2020
# REVISION:
#

set -e
set -o xtrace

# Sets the default locale. LC_ALL has precedence over other LC* variables.
unset LANG
unset LANGUAGE
LC_ALL=en_US.utf8
export LC_ALL

# Sets PATH. setup_*.sh uses useradd command
PATH=${PATH}:/usr/sbin:/sbin

# an unset parameter expansion will fail
set -u

# umask 022 is enough
umask 022

# defines environments
SRCDIR=$(cd $(dirname "$0") && pwd)

# Install the k2hdkc-trove-helper
sudo install -C -m 0755 -o root -v ${SRCDIR}/service_manager/scripts/k2hdkc-trove-helper /usr/libexec/k2hdkc-trove-helper
RESULT=$?
if test "${RESULT}" -ne 0; then
    echo "RESULT should be zero, not ${RESULT}"
    return 1
fi

# Install the k2hdkc-trove.service
sudo install -C -m 0644 -o root -v ${SRCDIR}/service_manager/k2hdkc-trove.service /lib/systemd/system/k2hdkc-trove.service
RESULT=$?
if test "${RESULT}" -ne 0; then
    echo "RESULT should be zero, not ${RESULT}"
    return 1
fi

sudo adduser k2hdkc
sudo mkdir -p /var/lib/k2hdkc/data
sudo mkdir -p /etc/k2hdkc

#
# Local variables:
# tab-width: 4
# c-basic-offset: 4
# End:
# vim600: expandtab sw=4 ts=4 fdm=marker
# vim<600: expandtab sw=4 ts=4
#
